### ISSUE TITLE
mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj	

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [SSBMTonberry/tileson#18]
Your examples have a lot of limitations to run them. I'm on Microsoft Visual Studio Professional 2019 Version 16.7.6
The project is set to Win32 (x86) as instructed.

**Comment by SSBMTonberry** [comment]
@TheMaverickProgrammer: When I first the demo it was something "quick and dirty" by request, that would build for all OSes, with the cost of some limitations like x86 for Windows. I haven't tried to build the examples in the newest master, as updating the examples is kinda the last thing I do before a release, but I'll boot into my Windows and see if I get the same error, and push a quick fix, eventually :slightly_smiling_face: 
I may fix, or at the very least improve the linking process in the examples for the `1.2.0` release, so it's not that dirty anymore :slightly_smiling_face: 

I'll get back to you!

**Comment by TheMaverickProgrammer** [comment]
I don't mean to self-plug here but my Swoosh project uses SFML. Feel free to ~~steal~~ copy my cmake script that uses git submodules to clone SFML as a dependency. I use this script for all my cross platform projects.

https://github.com/TheMaverickProgrammer/Swoosh

**Comment by SSBMTonberry** [comment]
Thanks! :smile: 
I have a cmake script using the proper way of building with SFML in another project, 
but yours may be better for what I know. Appreciate the share nonetheless, and I think it's about time to make the `example` project right.

**Comment by SSBMTonberry** [comment]
On a side note, after the next merge to master, only #13 remains for version `1.2.0`, which is all about stabilizing before the release and update the demo. The timing for this is perfect.

**Comment by SSBMTonberry** [comment]
Just tried to build the very latest `master` on Windows, but I did not encounter any issues...
Maybe there is a local debug setting in your VS causing the issue?
I used these settings (Using VS 2019 Pro `16.7.4`):
![bilde](https://user-images.githubusercontent.com/26206421/99900553-53661f80-2cb0-11eb-95e9-281c5e442110.png)

**Comment by SSBMTonberry** [comment]
Also: Took a look at your `Swoosh` project. Looks very nice, and the CMakeLists.txt file is one of the cleanest CMake files I've ever seen. Well done 😄 

I'll clean up the messy `examples` CMakeLists.txt before the release of `1.2.0`, but you should be able to build and run the latest `example` with the latest `master` using similar settings that I used above. As said: I suspect a local Debug-setting causing build issues for you.

**Comment by SSBMTonberry** [comment]
Did a quick google, and while old, this post seems related:
https://stackoverflow.com/questions/7668200/error-lnk2038-mismatch-detected-for-iterator-debug-level-value-0-doesnt

![bilde](https://user-images.githubusercontent.com/26206421/99900842-8a3d3500-2cb2-11eb-9aa6-202c72ea0b6e.png)

**Comment by SSBMTonberry** [comment]
@TheMaverickProgrammer : I've just cleaned up the `examples-CMakeLists.txt` and I've verified that the examples now were able to build on both `x86` and `x64` in my Windows-environment. Can you test if this solves your build issue? 
Thanks for addressing this issue. A cleanup in the examples build was very necessary, but I might not have cared too much about it if it had not been brought to my attention :slightly_smiling_face:

**Comment by TheMaverickProgrammer** [comment]
Im circling around back to this project soon I will let you know 👍
