### ISSUE TITLE
Isometric maps?

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [SSBMTonberry/tileson#19]
I couldn't run the examples to test but does your library make it easy to parse and draw isometric maps?

I like how simple the API is and allows me to fetch object properties directly without having to parse it myself. That's much more sane compared to other tiled libraries out there. I'd like to use it in my isometric project.

**Comment by SSBMTonberry** [comment]
Thank you very much, @TheMaverickProgrammer :smile:  I try to make `Tileson` as user friendly as possible, and make it easy to use with less code

To be honest I've never worked with isometric maps, but in my understanding they should be stored in the same way as regular `Tiled` maps, so all the data should be available :slightly_smiling_face: 
If you do find any flaws related to isometric maps, however, feel free to create an issue.
