### ISSUE TITLE
Retrieving Color property correctly.

### ISSUE THREAD

**Issue by LedLoaf** [SSBMTonberry/tileson#21]
Hello,

I'm wondering how you retrieve the Color property and then access the RGB values. I'm trying to make a text from TILED parse the correct color data and create a sf::Text. 

Thanks

**Comment by SSBMTonberry** [comment]
Hey!
You can retrieve the Text-object by going into your object layer where the text is, and get it using its name.
If your text object has an unique name, you can use the `firstObj("<yourname>")` function of the object layer, then get the "color" property as a `tson::Colori`. Here is an example using the very first example map `ultimate_test.json`:
```c++
tson::Colori color = map->getLayer("Object Layer")->firstObj("text")->get<tson::Colori>("color");
``` 
From here you can use the color.r/color.g/color.r/color.b/color.r/color.a as you like. You can also use the `asFloat() function, if you need to convert it to something representing a value from 0 to 1, commonly used with OpenGL :slightly_smiling_face: 

`get<T>("<property name>")` can be used for any property, but you need to know what the property represents. 

Hope this helps :smile:

**Comment by LedLoaf** [comment]
Hey, thanks for the assistance! 

So I still couldn't get it to work, but I discovered something while trying to mess around. Using ->getText()-> you have access to "text" and "wrap" and why not color? What I think is happening is I'm trying to access color, but I have to access the text list first?
Under the JSON file for the text object it says:
 "text": {"color":"#00ff00", "text":"Test Map", "wrap":true" },
So I'm thinking that could be the problem?

My text is on a GameObjects layer, I think you can only put them on GameObject layers, to begin with. 
Name is "TestText"
Font Text is  "Test Map"
**Code**
`auto gameObjects = m_map->getLayer("GameObjects");
	if (gameObjects != nullptr) {
		auto c = gameObjects->firstObj("TestText")->get<tson::Colori>("color");
		std::cout << gameObjects->firstObj("TestText")->getText().text << "\n";    // Correct
		auto color = sf::Color{ c.r,c.g,c.b };
		std::cout << color.r << ", " << color.g << ", " << color.b << "\n";              // ,  ,
		m_text.setFillColor(color);
	}`
Results: No font is shown.

**Comment by SSBMTonberry** [comment]
I looked into the details, and you are right. There is something missing!
The reason why is that it is missing in the `Tiled` json specification (which has been the base for `Tileson`):
https://doc.mapeditor.org/en/stable/reference/json-map-format/#text
![image](https://user-images.githubusercontent.com/26206421/101876100-2a88ca00-3b8c-11eb-867f-10fd910cb7ae.png)

When I look at the first example map, I see that there is an additional property for `color` which I must have missed:
![image](https://user-images.githubusercontent.com/26206421/101876644-07124f00-3b8d-11eb-849b-6614b61d5df7.png)

I'll look into this asap, and get back to you. `Tileson is as good as done for its `1.2.0` release, but I'll make sure this makes it into version`1.2.0` as well. 

Thank you very much for reporting! I'll get back to you :slightly_smiling_face:

**Comment by LedLoaf** [comment]
Great! 😂

I thought I was going crazy!

**Comment by SSBMTonberry** [comment]
Nope, you were right all along! 
This is why reporting issues is important :stuck_out_tongue:

Anyways, I just pushed a fix for this into master. A little copy/paste from my integration test:
```c++
    tson::Colori color = map->getLayer("Object Layer")->firstObj("text")->getText().color;
    REQUIRE(color.r == 254);
    REQUIRE(color.g == 254);
    REQUIRE(color.b == 254);
    REQUIRE(color.a == 255);
```
Can you verify that this fixes your problem? :slightly_smiling_face:

**Comment by LedLoaf** [comment]
Yay! It works! Thanks!

Few more questions if you don't mind. My computer doesn't like the u8strings used in **Tileson::Parse** for the error message and **ProjectFolder::loadData()**. So I had to go and change that and I just changed them to string. It says cannot cast from std::basic_string<char8_t> to std::basic_string<char> via functional cast.

Secondly,
While I was letting you work that out I was experimenting and seeing if I could put a custom property named ColorTest in the JSON file under the TextObject and it wasn't finding anything. I turned it into just an int, and nothing appeared in my cout statement. So I decided to get the vector of properties from the layers and cout them and there was nothing to show. I'm wondering if custom types aren't allowed and there are just predefined properties? I then used the add function from Property to create a Color attribute and it worked fine then. Also, there was a way to retrieve a map version and a vector version. The map version did actually show the name if I added it manually. 

Now, I am expanding basically on the example you provide. When you are parsing the file, do I have to do something more to get all the properties in the vector? I'd like to just be about to cout everything it's reading if that makes sense? It was a kind of version of debugging the problem making sure it was even reading the property "Color" at the time. I call it the cout trial and error solution! 😄

I appreciate the prompt fix and I am really liking this library and I appreciate all the work. Thanks and have a great night or day depending on where you are. 😁

**Comment by SSBMTonberry** [comment]
Thanks for your kind feedback 🙂 
For the `ProjectFolder::loadData()`-problem, my guess this is a platform implementation issue, which is the very last thing I go through before an actual release, so I wouldn't worry too much about it. I do my development using Linux, but I always make sure the examples are compiling on Windows and OS X before the actual release. Usually I have to fix some minor platform differences like that before a release.

When it comes to adding properties, I have to look on the details, but the library is a parser, so I would guess all property related stuff are defined as read-only by default. With that said: I have no problem allowing the user to add custom properties, if that is a feature that is wanted. It's a very low-risk change that I have no problems making. I'll look into it this weekend.

You should be able to get `PropertyCollection` of an object or tile using the `getProperties()`. A `PropertyCollection` also has a function called `getProperties()`, but the one inside the collection returns the actual property map, where the key is the name of the property, and the value is a `tson::Property`. Alternatively you can also call the `get()` function inside `PropertyCollection` to get a list of `tson::Property`-pointers to all existing properties 🙂

**Comment by SSBMTonberry** [comment]
@LedLoaf : Sorry, I think I read your message too quickly and misread some important details :stuck_out_tongue: 

You can actually add whatever custom property you want, but as it stands there is a requirement that you have an existing default/parameterless constructor if you use an own class.

Example:
```c++
class CustomProperty
{
    public:
        CustomProperty() = default;
        explicit CustomProperty(std::string str) : m_str{std::move(str)}
        {

        };

        [[nodiscard]] const std::string &getStr() const
        {
            return m_str;
        }

    private:
        std::string m_str{};
};

TEST_CASE( "Add custom property - expect working", "[property][custom]" ) {
    tson::PropertyCollection props;
    props.add("james", CustomProperty("CustomValue"), tson::Type::Undefined);
    CustomProperty custom = props.getValue<CustomProperty>("james");
    REQUIRE( custom.getStr() == "CustomValue" );
}
```
Does this answer your question? :slightly_smiling_face:

**Comment by SSBMTonberry** [comment]
As for `std::cout`-ing everything: It will not work with `tson::Color`-objects because it doesn't override the stream output operator (also known as `<<`). This could be implemented, though, but it'll be for the next release :slightly_smiling_face:

**Comment by LedLoaf** [comment]
Hey SSBMTonberry,

Sorry, been a bit busy. I am a bit confused though. So it should already parse any custom keys from the JSON file correct? For instance, in Tiled where the properties are you can add for example, "num" and assign it as 9. Irrelevant variable, but I'm sure there could be valuable variables. 

At the time, I had added "ColorTest" (something like that) as a property, which I actually just assigned an int value to see if it was even reading it. After getting the map of properties, I was unable to find it, or anything for that matter after `std::cout'ing` the names and values. It was for sure not even registering it when I was trying to retrieve it. 

```
 {
  "height":19, 
     "id":27, 
   "name":"TestText", 
    "rotation":0,            
"num":9,
    "text":
      {
          "color":"#00ff00",
           "text":"Test Map",
            "wrap":true
       },
   "type":"",
    "visible":true,
     "width":83,
     "x":100.625,
     "y":60
}
```

As you can see  `"num":9,` I added just because I was messing around and saw there could be used for adding values. And the reason I think I can't find any of the properties and `std::cout `them is the size is showing up 0. Perhaps it's clearing the vector at some point? I must be doing something wrong. 

What I am expecting is all those properties showing up, name, and value. **I can't access the vector or map because it's size is 0.**

```
auto prop = m_map->getLayer("GameObjects");
		std::cout << "Size: " << prop->getProperties().get().size() << "\n";                                                // Output: 0
		std::cout << "Num: " << prop->getObj(27)->getProperties().getProperty("num") << "\n";          // Output: 0
		for (auto& [name, value] : prop->getProperties().getProperties()) {                                                // Size Output: 0

			if (value.getType() == tson::Type::String)
				std::cout << name << " " << std::any_cast<std::string>(value) << "\n";
			else if (value.getType() == tson::Type::Float)
				std::cout << name << " " << std::any_cast<float>(value) << "\n";
			else if (value.getType() == tson::Type::Int)
				std::cout << name << " " << std::any_cast<int>(value) << "\n";
			else if (value.getType() == tson::Type::Boolean)
				std::cout << name << " " << std::any_cast<bool>(value) << "\n";
			else
				std::cout << name << " " << std::any_cast<int>(value) << "\n";
		}
```

**Comment by SSBMTonberry** [comment]
No problem!
I misunderstood what you tried to achieve, but now I think I get it.
When editing a Tiled json manually, you must remember that `Tileson` can only understand what `Tiled` would understand.
Neither `Tiled` nor `Tileson` would have any idea what `num` is in your json, because it's not added as a property, but rather as a variable in a `tson::Object`. With that said, what you are trying to do is achievable 🙂 

If you'd want to to `num` as a property, you could do something like I've done here:
```json
{
       "height":19,
       "id":12,
       "name":"text",
       "properties":[
       {
              "name":"num",
              "type":"int",
              "value":9
       }],
       "rotation":0,
       "text":
       {
       "color":"#fefefe",
       "text":"Tileson - Demo Map",
       "wrap":true
       },
       "type":"",
       "visible":true,
       "width":170,
       "x":144,
       "y":0
}
```

Then I just get it like this: 
```c++
int num = map->getLayer("Object Layer")->firstObj("text")->get<int>("num");
```
It would otherwise show up in your for-loop like any other property would 🙂

**Comment by LedLoaf** [comment]
Appreciate it, great! Merry Christmas.
