### ISSUE TITLE
drawingRect does not take spacing and margin into account

### ISSUE THREAD

**Issue by lmreia** [SSBMTonberry/tileson#31]
The variable m_drawingRect is assigned by the function tson::Tile::performDataCalculations().  This function does not take the spacing and margin of the tileset into account when calculating the offsetX and offsetY, so the resulting rect does not represent the actual tile.
I have not tested it, but maybe you could replace it by something like:

int offsetX = m_tileset->getMargin() + tileModX * (m_map->getTileSize().x + m_tileset->getSpacing() + 2*m_tileset->getMargin()) 

and similar to Y

**Comment by SSBMTonberry** [comment]
@lmreia : Thank you for a well described issue! It makes sense to me that this has been forgotten, as I never use margins or spacing in my personal tilesets 😛 Regardless this is a fatal flaw in my implementation, and I will push a fix to master in the coming days!

**Comment by SSBMTonberry** [comment]
@lmreia : A fix for this issue can now be found in master.
You can find the latest `tileson.hpp` [here](https://github.com/SSBMTonberry/tileson/tree/master/single_include).

Thanks again for reporting :slightly_smiling_face:
