### ISSUE TITLE
Animated Tiles

### ISSUE THREAD

**Issue by hsdk123** [SSBMTonberry/tileson#32]
Hi, I was wondering how I'd fetch info for animated tiles

ex. https://www.youtube.com/watch?v=ZNEH-rFQ7Ys

**Comment by SSBMTonberry** [comment]
Hello, @hsdk123 , and my apologies for answering your post so late.
If you haven't figured it out already, the animation data is located inside the ` tson::Tile` class.
It's not really showcased in the demo, even though there are animation data on one of the tiles. A quick example how i retrieve animation data from a known Tile in one of my unit tessts is:
` ` ` c++
map->getTileset("demo-tileset")->getTile(36)->getAnimation()
` ` ` 

Get animation will give you a vector of frames. This is what the code itself looks like:
![image](https://user-images.githubusercontent.com/26206421/108598504-3ebc2500-738e-11eb-949c-376594fb878c.png)

And the `tson::Frame` class looks like this:
![image](https://user-images.githubusercontent.com/26206421/108598541-6e6b2d00-738e-11eb-9f91-fcc2c99ca259.png)

Again: Sorry for the late reply, and I hope this helped :)

I'll add this issue to the v1.3.0 release, to remind myself to include an example of animations in the demo.

**Comment by SSBMTonberry** [comment]
Example is now updated to showcase the new `tson::Animation` class and how to use it. Right now this must be compiled in the `master` branch (which requires the `BUILD_EXAMPLES` flag in CMake to be activated)
