### ISSUE TITLE
Support for external tilesets

### ISSUE THREAD

**Issue by Manlibear** [SSBMTonberry/tileson#33]
Would it be possible to support external tilesets (i.e. non-embedded ones)? The library is incredible, far and away the best one out there, but if I make a change to an embedded tileset having to go and change that for all maps is rather annoying!

**Comment by SSBMTonberry** [comment]
Thank you very much for your nice words! :slightly_smiling_face: 
More people have been asking for this feature, and I see that it can be useful when you have a lot of maps with external tile information. I try to make external files a minimum, but I'll make an exception for Tilesets.

I'll add this to the current milestone.

**Comment by SSBMTonberry** [comment]
@Manlibear: You should now be able to use external tilesets using the latest version of Tileson in `master` (check the `single_include` folder). Keep in mind that the external tileset must be in a json-format, but they should be automatically resolved by `Tileson` if the relative path inside the Tiled-map is correct :slightly_smiling_face: 
Please give feedback if you end up testing this feature. I think my unit tests should cover everything, though.

Also: Keep in mind that Tiled v1.5 has some breaking changes that are not implemented yet. Mostly related to Wangsets, but I'd still recommend using an earlier version of Tiled before v1.5 is officially supported, though you should be fine reading old maps if wang-sets or `terrains` are not in use.
