### ISSUE TITLE
Tileson::parse() doesn't parse, printing"expected value, got '<' (60)"

### ISSUE THREAD

**Issue by KRC2000** [SSBMTonberry/tileson#42]
Hi! Im trying to use this library but i have a problem, any fs::path that I pass to method Tileson::parse() doesn't work, some of them cause printing "expected value, got '<' (60)" wich is hard to decrypt. 
Case 1: json file is in the VS project folder
![image](https://user-images.githubusercontent.com/47914319/123646829-3b4f1380-d830-11eb-8664-5449e09d155c.png)
Console is empty
![image](https://user-images.githubusercontent.com/47914319/123646936-5588f180-d830-11eb-9881-796aa3f5cf1b.png)
Tried also with these pathes:
".tileMap1sss.json"
"/tileMap1sss.json"
"./tileMap1sss.json"
Case 2: json file is in the folder "Map" that located in the VS project folder
![image](https://user-images.githubusercontent.com/47914319/123647706-fc6d8d80-d830-11eb-8bcf-9dd91cf849c0.png)
Message printed
![image](https://user-images.githubusercontent.com/47914319/123647788-114a2100-d831-11eb-8ce8-ad4c8376f484.png)
Tried also with these pathes:
".Map/tileMap1sss.json"
"/Map/tileMap1sss.json"
"./Map/tileMap1sss.json"

I will be really happy if you can help with it, not sure if its ok to create issue because of this. Also I'm sorry for my English I hope it's clear what my problem is.

**Comment by SSBMTonberry** [comment]
Hello, and sorry for this late reply!
And yes, this is absolutely the right place to post this! 🙂 

My first thought is that, unless you have embedded everything into your json-file, that you have external tilesets in tsx-format, which indicates that they contain xml data. External tilesets are supported in the latest version of Tileson, but they have to be in .json format to work, as Tileson is a json-parser.

If this does not solve your problem, feel free to send me the files in that project, and I'll look into the details for you 😄

**Comment by KRC2000** [comment]
Hey! Thanks for a reply! Fixed it just like you said. Exported tileset as json file, and then edited map json file by changing tileset path from  "tileSet1.tsx" "tileSet1.json". Thank you very much! Also i should read descriptions more carefully XD You literally wrote about this in readme) 
![image](https://user-images.githubusercontent.com/47914319/124346533-00f6c500-dbe8-11eb-8593-48c7246802af.png)
Anyways thank you so much for your lib and support!

**Comment by SSBMTonberry** [comment]
You're welcome! Glad it worked out 😄  
Yeah, I've tried to list the important details in the README, to prevent people to run into problems like this, but I understand that most people would not just read the whole README, so it's all good 🙂
