### ISSUE TITLE
Fix cl compiler warnings

### ISSUE THREAD

**Issue by Laguna1989** [SSBMTonberry/tileson#43]
It seems that when compiling tileson with the visual studio compiler (cl version 19.29.30038.1) there are some compiler warnings. Those are not critical and most of them can be fixed by adding a cast. Please see the attached log file

[cl_comiler_warnings.txt](https://github.com/SSBMTonberry/tileson/files/7198311/cl_comiler_warnings.txt)
 
None of them seem critical to me - except a user would use more `Gid`s than uint32_t  could contain.

**Comment by SSBMTonberry** [comment]
Reviewed your pull request and all looks fine. Thank you for contributing to the project :slightly_smiling_face:

**Comment by Laguna1989** [comment]
Thank you for the feedback and thanks for merging the PR. If you want to tackle a rework of the types at some point and need someone to brainstorm or pair with, just let me know.
