### ISSUE TITLE
IJson and IDecompressor have no virtual destructor

### ISSUE THREAD

**Issue by matthew-nagy** [SSBMTonberry/tileson#47]
Despite being pure virtual classes, their destructors have not been explicitly marked as virtual. This can cause derrived classes to not have their destructors called correctly.
It also makes clang++ on linux throw me a warning a mile long, and adding these changes to my forked version fixed these issues. If you'd like, I can create a pull request.

**Comment by SSBMTonberry** [comment]
Thanks for your issue! 🙂  
Feel free to create a pull request on this.
