### ISSUE TITLE
Create an new release

### ISSUE THREAD

**Issue by cvlnomen** [SSBMTonberry/tileson#48]
I just spend three hours finding out why my program was throwing thousands of memory leaks. Eventual, I discovered that the IJson and IDecompressor classes were missing a destructor. I wanted to create an issue and pull request to notify you about this issue, but then I saw [someone else fixed the same problem](https://github.com/SSBMTonberry/tileson/commit/32e5552fc8551012b6985d47f27ff63477798f5d) 14 days ago. I hope you will make a new release, so that other people won't make the same mistake as I did!

**Comment by SSBMTonberry** [comment]
It would be weird to create an entire new release for every single bug that is fixed, but I was panning to add a list of fixes that are not presented in a current release, and can be found in master. I've been doing this previously, but I simply forgot this time around. I will close this issue when that is done. The short answer is no matter what: Using `master` will be your best bet. I never merge anything halfway done into master, so it should be the most stable option.

**Comment by SSBMTonberry** [comment]
I've now added a `Unreleased features available in the master-branch` section to the `README`. Hopefully that prevents others to have the same struggle.
