### ISSUE TITLE
Having trouble with the parser

### ISSUE THREAD

**Issue by Megarev** [SSBMTonberry/tileson#49]
```cpp
#include <iostream>
#include "tileson.hpp"

int main() {
	tson::Tileson parser;
	std::unique_ptr<tson::Map> map = parser.parse(fs::path("./files/map.json"));

	if (map->getStatus() == tson::ParseStatus::MissingData) {
		std::cerr << "Map data not loaded" << std::endl;
		return -1;
	}


	return 0;
}
```

I've a simple program like so, when I run it, the console shows
![image](https://user-images.githubusercontent.com/64357296/143669197-250cd1fc-d136-428f-b094-f9141349807a.png)
I've definitely checked the json is in the right directory, but here's the json file as well https://pastebin.com/pQ155GBg
I've been debugging for hours, but I can't seem to figure out the issue
Please help me with resolving the issue

Thanks

**Comment by SSBMTonberry** [comment]
Hello, @Megarev !
Of course I'll help you :slightly_smiling_face: 

I took a small look into your json file, and noticed that your tileset has a tsx-extension, which means that it is in xml-format, and not .json, as Tileson requires. If you change the tileset to json format it should work. Actually there was another guy having the same issue a while ago. [See issue #42](https://github.com/SSBMTonberry/tileson/issues/42)

**Comment by Megarev** [comment]
The console messages seem to have went away
Thanks a lot for the help :)
