### ISSUE TITLE
Remove warnings

### ISSUE THREAD

**Issue by LeifHenriksen** [SSBMTonberry/tileson#51]
Hi, I am compiling tileson with -Wall -Wextra -Wpedantic and gcc version 9.3.0 and I am getting some warnings, I have fixed three of them that you can see in this file [warnings.txt](https://github.com/SSBMTonberry/tileson/files/7855898/warnings.txt). If you agree I can create a pull request with the changes.

There are other warnings that involve std::move that I can also fix if you want, you can see them here [all_warnings.txt](https://github.com/SSBMTonberry/tileson/files/7855927/all_warnings.txt). I didn't remove the std::move because maybe there is some reason for it that I am not aware of.
 
Thank you.

**Comment by SSBMTonberry** [comment]
Hello @LeifHenriksen , and thank you for the issue :slightly_smiling_face: 
Feel free to fix any warnings there, and I can do a review if you create a PR on it. Just remember that none of the changes must be done in the `tileson.hpp` directly, as this file is generated (ref the `CONTRIBUTION.md` ). Also please verify that the demo and the tests still works after your changes, and it should be fine :+1:

**Comment by SSBMTonberry** [comment]
- This should have been fixed with this recent PR: #90
