### ISSUE TITLE
Make sure Tileson has full C++20 support!

### ISSUE THREAD

**Issue by SSBMTonberry** [SSBMTonberry/tileson#53]
- Ref #52 

It seems like there are problems when using C++20 with Tileson on Windows. Make sure Tileson builds OK when using C++20 and C++17 on all major compilers. That is `MSVC`, `GCC` and `Clang`

**Comment by ProfAndreaPollini** [comment]
Hi, I tried to fix the lib for c++20. I made a very dirty work, so it's not good for a PR, but it works for me :)

**Comment by SSBMTonberry** [comment]
@ProfAndreaPollini : Feel free to share your `dirty` fix here for other users to see until my official fix is implemented 🙂
