### ISSUE TITLE
Tile layer data compression

### ISSUE THREAD

**Issue by mfuluat** [SSBMTonberry/tileson#65]
Hi there, as far as I understand tileson support whole file compression, what about tile layer data compression? When I choose, for instance, Base64 (gzip or Zstandard), layer.getTileObjects() returns nothing, but no problem if I choose CSV or Base64 (not compressed).
Do I miss something? 
Thanks in advance.

By the way, great library 😊👍

**Comment by SSBMTonberry** [comment]
Hey, @mfuluat, and thank you for your nice words :)
Compression on the layer level is not supported by `Tileson`. I did consider this at some point, but I found that having compession on layer basis is inefficient, so I decided not to support it in the end. As you already have discovered, `Tileson` is able to read fully `LZMA`-compressed maps using [pocketlzma](https://github.com/SSBMTonberry/pocketlzma).

With that said I think I added support for the possibility to add your own decompression logic by adding it to a `DecompressorContainer` which uses names to find out whether it is related or not. It will require that you use the `IDecompressor` interface and implement your own logic tho, but if you had a name `gzip` on something like that it should get the job done. Of course you will need to find a library handling the decomporession itself, but here is some code to explain the steps you will have to do (Also: you can use the `Base64Decompressor`(i know it''s not decompression per se, but the process is the same) as a reference to how to implement your own logic for gzip) :

GzipDecompressor:
```c++
class GzipDecompressor : public tson::IDecompressor<std::string_view, std::string>
{
    public:
        [[nodiscard]] inline const std::string &name() const override;

        inline std::string decompress(const std::string_view &s) override;

        inline std::string decompressFile(const fs::path &path) override;
        inline std::string decompress(const void *data, size_t size) override;

    private:
        inline static const std::string NAME = "gzip";
};

const std::string &GzipDecompressor::name() const
{
    return NAME;
}

std::string GzipDecompressor::decompress(const std::string_view &s)
{
    //Hwere you will need to do your decompression logic
}

std::string GzipDecompressor::decompressFile(const fs::path &path)
{
    return std::string();
}

std::string GzipDecompressor::decompress(const void *data, size_t size)
{
    return std::string();
}
```

Adding your decompressor:
```c++
    tson::Tileson tileson;
    tileson.decompressors()->add<GzipDecompressor>();
    //After this it should be called automatically when you parse something that contains the gzip name.
```

I cannot guarantee 100% that it will work, but if you give it a try, please tell me if you get it to work. I think the intention of this design was to make this possible for anyone to add layer based compression by just extending this interface, but it's a long time ago, and I think the only thing that has been tested here is handling of base64  :slightly_smiling_face:

**Comment by mfuluat** [comment]
_"I did consider this at some point, but I found that having compession on layer basis is inefficient, so I decided not to support it in the end."_, 
I agree with you on this, at the end, it may not be as efficient as it seem to handle sub-fields individually.
Nevertheless, I will check it out and try to get it work. If so, I will inform you 👍.

Thanks.
