### ISSUE TITLE
Add stricter compile flags when building tests

### ISSUE THREAD

**Issue by SSBMTonberry** [SSBMTonberry/tileson#86]
To make `Tileson` more clean and less error prone, the flags `-Wall -Wextra -Werror` should be added to the test build, to make CI a stricter process. This will be done after the CI is fixed and a proper `MAC` build using `Clang` is implemented.

See #84 for the discussion.

Big thanks to @dmlary for the suggestion :slightly_smiling_face:

**Comment by SSBMTonberry** [comment]
@dmlary : I've fixed the CI now, so feel free to look into this if you want. :slightly_smiling_face: 
That is:
- Adding the mentioned compile flags.
- Fix the errors that may show up.

If you reply, I think I may be able to assign this task directly to you :smile:

**Comment by dmlary** [comment]
Question:
tests/tson_files_mapper.h and tests/tson_files.h are effectively the same contents, one mapping to the other,  are both needed?

The MSVC compiler errors will take a bit longer to sort out.

**Comment by SSBMTonberry** [comment]
> Question: tests/tson_files_mapper.h and tests/tson_files.h are effectively the same contents, one mapping to the other, are both needed?
> 
> The MSVC compiler errors will take a bit longer to sort out.

Yes, they are both needed. The reason why `tson_files_mapper.h` exists is that `tson_files.h` gets way too heavy for the `IDE` to parse when you have a lot of files there, and will eventually break autocomplete/intellisense. By referring to the mapper, which does contain all the bytes, that problem is no issue. These files are generated by [f2src](https://github.com/SSBMTonberry/f2src) which is a program for making files in-memory.
