### ISSUE TITLE
Object parse always assumes the current project is nullptr

### ISSUE THREAD

**Issue by matthew-nagy** [SSBMTonberry/tileson#92]
In `tson::Object::parse`, inside the lambda to add properties, the project from the Map is not passed in. This makes it default to nullptr. This means when properties of type Class are parsed, they are never given a value.

This can be fixed by changing the lambda to also take in `m_map->getProject()`.

`std::for_each(properties.begin(), properties.end(), [&](std::unique_ptr<IJson>& item)
			{
				m_properties.add(*item, m_map->getProject());
			});`

The setup I was using that caused this bug was to make a tson::Project, then make a tson::Tileson with that project as an argument, then using tson::Tileson::parse. I'm adding this here just in case I missed some step and this was actually due to misuse.

I have a version with this working if you want a quick pull request.

**Comment by SSBMTonberry** [comment]
Thanks for your issue, @matthew-nagy !

I've sadly not been able to work with Tileson for a couple of months, but the last issue I was working with until I got a bit inactive was #87 , which very well may be caused (fully or partially) by what you describe here. 

As long as you can verify that the existing tests are okay after your change, and you make sure to run the `amalgamate` script located in tools to update the `single header`: I would be very happy to get a pull request on this :smile:
Just make sure that you do the changes  in the code inside the `include` folder, as the `tileson.hpp` file is generated.
Whenever you push the PR, I'll do a review after work, and eventually merge it. Thanks!

I'm planning to work on getting the finishing touches for `v1.4.0` done by the end of june. I've been quite busy with work and other projects this year, which have made me inactive on the development of `Tileson` for a couple of months, but `Tileson` is not dead :stuck_out_tongue_closed_eyes:
